[build]
  command = "npm run export"
  functions = "lambda" #  netlify-lambda reads this

[[redirects]]
  from = "/studies/*"
  to = "/studies/[slug].html"
  status = 200
  force = true

[[redirects]]
  from = "/tasks/*"
  to = "/tasks/[slug].html"
  status = 200
  force = true

[[redirects]]
  from = "/join/*"
  to = "/join/[step].html"
  status = 200
  force = true

[[redirects]]
  from = "/data/study"
  to = "/data/study.html"
  status = 200
  force = true
