[build]
  command = "npm run export"
  functions = "lambda" #  netlify-lambda reads this

[[redirects]]
  from = "/study/*"
  to = "/study/[slug].html"
  status = 200
  force = true

[[redirects]]
  from = "/*"   
  to = "/index.html"
  status = 200
